### ISSUE TITLE
在连接了不存在的地址之后直接崩溃了

### ISSUE THREAD

**Issue by huankong233** [bin-tenkuu/node-go-cqwebsocket#8]
问题如题，而且不能被捕获

~~~
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:8081
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (c:\Users\huan_kong\Desktop\code\kkbot-ts\node_modules\.pnpm\ws@7.5.9\node_modules\ws\lib\websocket.js:895:13)
    at ClientRequest.<anonymous> (c:\Users\huan_kong\Desktop\code\kkbot-ts\node_modules\.pnpm\ws@7.5.9\node_modules\ws\lib\websocket.js:752:5)
    at ClientRequest.emit (node:events:514:28)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 8081
}
~~~

**Comment by huankong233** [comment]
node -v
v18.17.0
